---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - 'community.general'
  - 'ansible.posix'
  - 'community.mysql'
  - 'community.crypto'

roles:
  - name: 'oxlorg.apache2'
    src: 'git+https://github.com/O-X-L/ansible-role-apache2'

  - name: 'oxlorg.certs'
    src: 'git+https://github.com/O-X-L/ansible-role-certs'

  - name: 'oxlorg.mariadb'
    src: 'git+https://github.com/O-X-L/ansible-role-mariadb'
