---

- name: Django | Checking config
  ansible.builtin.fail:
    msg: "The required configuration was not provided!
    Needed: 'django', 'django.sites'"
  when: >
    django is undefined or
    django.sites is undefined or
    django.sites | length == 0

- name: Django | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
