---

- name: Apache | Wrapper | Configuring django project
  include_tasks: django.yml
  args:
    apply:
      vars:
        django_base: "{{ django_projects[site_django_project].base | default(django_default.base) }}"
        django_root: "{{ django_projects[site_django_project].root | default(django_default.root) }}"
        site_root: "{{ django_root }}"
        django_root_venv: "{{ django_projects[site_django_project].root_venv | default(django_default.root_venv) }}"
        django_root_static: "{{ django_projects[site_django_project].root_static | default(django_default.root_static) }}"
        django_url_static: "{{ django_projects[site_django_project].url_static | default(django_default.url_static) }}"
        django_venv_python: "{{ django_projects[site_django_project].venv_python | default(django_default.venv_python) }}"
        django_mods: "{{ django_projects[site_django_project].mods | default([]) }}"
        django_pythonpaths: "{{ django_projects[site_django_project].pythonpaths | default([]) }}"
        django_db: "{{ django_projects[site_django_project].db | default([]) }}"
  when:
    - site_config == 'django'
    - site_django_project != ''
  no_log: true

- name: Apache | Wrapper | Configuring apache site
  include_tasks: site.yml
  when: site_config != 'django'
